version: '3.8'

services:
  fastapi:
    build:
      context: ./virazhapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"

  nextjs:
    build:
      context: ./cafevirage
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"